"""New Migration

Revision ID: 4e7bc7e8f1b3
Revises: d308a25642b5
Create Date: 2021-10-29 18:53:20.517176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7bc7e8f1b3'
down_revision = 'd308a25642b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
